import { getHistoricalSolData } from "../backtesting/historicalMarketService.ts";
import { normalizeHistoricalCandles } from "../backtesting/marketCandles.ts";
import { backtestExecutionConfig } from "../backtesting/backtestConfig.ts";
import { parameterSchemas } from "../optimization/parameterSchemas.ts";
import { momentumStrategyConfig } from "../strategy/momentumStrategy.ts";
import { paperTradingConfig } from "../trading/tradingConfig.ts";
import { runExtendedValidationArena } from "../validation/extendedValidation.ts";
import { validationWindowConfig } from "../validation/validationWindows.ts";
import { aggregateAnchorResults } from "./multiAnchor.ts";
import { generateResearchAnchors, normalizeResearchAnchor } from "./anchorValidation.ts";
import { RESEARCH_CACHE_TTL_MS } from "./researchCache.ts";
import { canonicalize, createResearchRunId, fingerprintDataset, fingerprintResult, researchVersions } from "./researchIdentity.ts";
import { createResearchSummary, serializedBytes, sanitizeForJson, withSummaryAccess } from "./researchSummary.ts";
import { FileSystemResearchStore, isStoredResearchRecord, MemoryResearchStore, RESEARCH_HISTORY_LIMIT, RESEARCH_STORE_SCHEMA_VERSION, validateResearchNote } from "./researchStore.ts";
import type { ResearchStore } from "./researchStore.ts";
import type { HistoricalDataSet } from "@/types/backtesting";
import type { ExtendedValidationArena } from "@/types/extendedValidation";
import type { AnchorResult, MultiAnchorResult, ResearchConfiguration, ResearchManifest, ResearchPersistenceStatus, ResearchStoreStatus, StoredResearchRecord, StoredResearchResponse } from "@/types/research";

const config={strategy:momentumStrategyConfig,paperTrading:paperTradingConfig,risk:paperTradingConfig,execution:backtestExecutionConfig};
export const researchMemoryStore=new MemoryResearchStore();
const configuredStore=process.env.VEYRIX_RESEARCH_STORE==="filesystem"||process.env.NODE_ENV==="development"?new FileSystemResearchStore(process.env.VEYRIX_RESEARCH_STORE_PATH):null;
let durableUnavailable=false;
const inflight=new Map<string,Promise<{record:StoredResearchRecord<ExtendedValidationArena>;persistence:ResearchPersistenceStatus}>>();

function researchConfiguration(timeframe:"180D"|"365D",anchor:string):ResearchConfiguration{return{strategies:["momentum","moving_average","mean_reversion"],timeframe,anchor,validationMethod:"ALL",versions:{...researchVersions,cacheSchemaVersion:RESEARCH_STORE_SCHEMA_VERSION},execution:backtestExecutionConfig,risk:{stopLossPercent:paperTradingConfig.stopLossPercent,takeProfitPercent:paperTradingConfig.takeProfitPercent,positionSizePercent:paperTradingConfig.positionSizePercent},validation:validationWindowConfig,historical:{source:"Coinbase Exchange",pair:"SOL-USD",granularitySeconds:21600}}}
function manifest(configuration:ResearchConfiguration,data:HistoricalDataSet,id:string,datasetFingerprint:string):ResearchManifest{return{schemaVersion:"veyrix-research-v1",researchRunId:id,generatedAt:new Date().toISOString(),historicalStart:data.observations[0]?.timestamp??"",historicalEnd:data.observations.at(-1)?.timestamp??"",candleInterval:"6 hours",candleCount:data.observations.length,source:"Coinbase Exchange",dataQuality:data.quality,strategies:configuration.strategies,strategyParameterGrids:Object.fromEntries(Object.entries(parameterSchemas).map(([id,schema])=>[id,schema.parameters.map(parameter=>({key:parameter.key,values:parameter.values}))])),executionAssumptions:configuration.execution,riskSettings:configuration.risk,validationMethod:configuration.validationMethod,validationSettings:configuration.validation,scoringModelVersions:configuration.versions,benchmarkSettings:{fullExposurePercent:100,matchedExposurePercent:10},datasetFingerprint}}
const active=(record:StoredResearchRecord,now:number)=>record.pinned||Date.parse(record.expiresAt)>now;

export function getResearchStoreStatus():ResearchStoreStatus{return{memory:"AVAILABLE",durable:configuredStore?(durableUnavailable?"UNAVAILABLE":"CONFIGURED"):"NOT_CONFIGURED",provider:configuredStore?"filesystem":null,schemaVersion:RESEARCH_STORE_SCHEMA_VERSION}}
async function readDurable<T>(id:string):Promise<StoredResearchRecord<T>|null>{if(!configuredStore)return null;try{const record=await configuredStore.get<T>(id);durableUnavailable=false;return record}catch{durableUnavailable=true;return null}}

export async function runStoredResearch(timeframe:"180D"|"365D",anchorInput?:string,now=Date.now()):Promise<StoredResearchResponse<ExtendedValidationArena>>{
 const anchor=anchorInput?normalizeResearchAnchor(anchorInput,now):new Date(Math.floor(now/21600000)*21600000).toISOString();if(!anchor)throw new Error("Invalid anchor");
 const totalStart=performance.now(),historyStart=performance.now(),data=await getHistoricalSolData(timeframe,now,anchor),historicalRetrievalMs=performance.now()-historyStart,normalStart=performance.now(),candles=Object.freeze(normalizeHistoricalCandles(data.observations).candles.map(candle=>Object.freeze({...candle}))),normalizationMs=performance.now()-normalStart,datasetFingerprint=fingerprintDataset(candles),configuration=researchConfiguration(timeframe,anchor),id=createResearchRunId(configuration,datasetFingerprint);
 const memory=await researchMemoryStore.get<ExtendedValidationArena>(id);if(memory&&active(memory,now)){const persistence=memory.compactSummary.persistenceStatus,summary=withSummaryAccess(memory.compactSummary,"MEMORY_HIT",persistence);return{source:"MEMORY_HIT",persistenceStatus:persistence,cachedAgeMs:Math.max(0,now-Date.parse(memory.createdAt)),summary,record:memory}}
 const stored=await readDurable<ExtendedValidationArena>(id);if(stored&&active(stored,now)){await researchMemoryStore.put(stored);const summary=withSummaryAccess(stored.compactSummary,"STORE_HIT","PERSISTED");return{source:"STORE_HIT",persistenceStatus:"PERSISTED",cachedAgeMs:Math.max(0,now-Date.parse(stored.createdAt)),summary,record:stored}}
 const existing=inflight.get(id);if(existing){const reused=await existing,summary=withSummaryAccess(reused.record.compactSummary,"IN_FLIGHT_REUSED",reused.persistence);return{source:"IN_FLIGHT_REUSED",persistenceStatus:reused.persistence,cachedAgeMs:null,summary,record:reused.record}}
 const job=(async()=>{await new Promise<void>(resolve=>setImmediate(resolve));const analysisStart=performance.now(),arena=sanitizeForJson(runExtendedValidationArena(candles,config,Number(timeframe.slice(0,-1)),data.quality)),analysisMs=performance.now()-analysisStart,totalMs=performance.now()-totalStart,resultFingerprint=fingerprintResult(arena),createdAt=new Date().toISOString(),expiresAt=new Date(Date.now()+RESEARCH_CACHE_TTL_MS).toISOString(),timing={historicalRetrievalMs,normalizationMs,parameterSensitivityMs:analysisMs,validationMethodMs:analysisMs,regimeAnalysisMs:analysisMs,strategyArenaMs:analysisMs,analysisMs,totalMs},researchManifest=manifest(configuration,data,id,datasetFingerprint),initial=createResearchSummary({runId:id,createdAt,timeframe,anchor,datasetFingerprint,resultFingerprint,durationMs:totalMs,arena}),sizes={summaryBytes:0,detailedBytes:serializedBytes(arena),storedRecordBytes:0};let record:StoredResearchRecord<ExtendedValidationArena>={schemaVersion:RESEARCH_STORE_SCHEMA_VERSION,researchRunId:id,createdAt,expiresAt,configuration,manifest:researchManifest,resultFingerprint,datasetFingerprint,compactSummary:{...initial,sizes},detailedResult:arena,timing,sizes,pinned:false,note:null};sizes.summaryBytes=serializedBytes(record.compactSummary);sizes.storedRecordBytes=serializedBytes(record);record={...record,sizes:{...sizes},compactSummary:{...record.compactSummary,sizes:{...sizes}}};let persistence:ResearchPersistenceStatus=configuredStore?"PERSISTED":"MEMORY_ONLY";if(configuredStore)try{await configuredStore.put(record);durableUnavailable=false}catch{persistence="STORE_WRITE_FAILED";durableUnavailable=true}record={...record,compactSummary:{...record.compactSummary,persistenceStatus:persistence}};await researchMemoryStore.put(record);return{record,persistence}})();
 inflight.set(id,job);try{const computed=await job,summary=withSummaryAccess(computed.record.compactSummary,"COMPUTED",computed.persistence);return{source:"COMPUTED",persistenceStatus:computed.persistence,cachedAgeMs:null,summary,record:computed.record}}finally{inflight.delete(id)}
}

/** V0.12 compatibility facade. New APIs use runStoredResearch and compact summaries. */
export async function runCachedResearch(timeframe:"180D"|"365D",anchorInput?:string,now=Date.now()){const response=await runStoredResearch(timeframe,anchorInput,now);return{cacheStatus:response.source==="MEMORY_HIT"||response.source==="STORE_HIT"?"HIT":response.source==="COMPUTED"?"MISS":"IN_FLIGHT_REUSED",cachedAgeMs:response.cachedAgeMs,record:{schemaVersion:"veyrix-cache-v1"as const,researchRunId:response.record.researchRunId,configuration:response.record.configuration,manifest:response.record.manifest,createdAt:response.record.createdAt,expiresAt:response.record.expiresAt,result:response.record.detailedResult,resultFingerprint:response.record.resultFingerprint,timing:response.record.timing}}}
export async function getResearchRecord(runId:string){const memory=await researchMemoryStore.get(runId);if(memory)return memory;const stored=await readDurable(runId);if(stored)await researchMemoryStore.put(stored);return stored}
export async function listResearchSummaries(limit=RESEARCH_HISTORY_LIMIT){const memory=await researchMemoryStore.list(limit);let stored:StoredResearchRecord[]=[];if(configuredStore)try{stored=await configuredStore.list(limit);durableUnavailable=false}catch{durableUnavailable=true}const unique=new Map<string,StoredResearchRecord>();for(const record of [...memory,...stored])unique.set(record.researchRunId,record);return[...unique.values()].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,Math.min(limit,RESEARCH_HISTORY_LIMIT)).map(record=>record.compactSummary)}
export async function updateResearchMetadata(runId:string,input:{pinned?:boolean;note?:unknown}){if(!configuredStore||!configuredStore.supportsPinning)throw new Error("Durable pinning is unavailable");const record=await getResearchRecord(runId);if(!record)throw new Error("Research run not found");const updated={...record,pinned:input.pinned??record.pinned,note:input.note===undefined?record.note:validateResearchNote(input.note),compactSummary:{...record.compactSummary,pinned:input.pinned??record.pinned,note:input.note===undefined?record.note:validateResearchNote(input.note)}};await configuredStore.put(updated);await researchMemoryStore.put(updated);return updated.compactSummary}
export async function runMultiAnchorResearch(timeframe:"180D"|"365D",latestInput?:string,now=Date.now()):Promise<MultiAnchorResult>{const latest=latestInput?normalizeResearchAnchor(latestInput,now):new Date(Math.floor(now/21600000)*21600000).toISOString();if(!latest)throw new Error("Invalid latest anchor");const anchors=generateResearchAnchors(latest),anchorResults:AnchorResult[]=[];for(const anchor of anchors){const started=performance.now(),response=await runStoredResearch(timeframe,anchor,now),arena=response.record.detailedResult,summaries=arena.entries.map(entry=>({strategyId:entry.strategyId,averageOosReturnPercent:entry.methods.reduce((sum,method)=>sum+(method.averageOutOfSampleReturnPercent??0),0)/entry.methods.length,multiRegimeRobustnessScore:entry.multiRegime.multiRegimeRobustnessScore??0,researchScore:entry.researchScore??0,matchedBeatRatePercent:entry.averageMatchedBeatRatePercent??0,rank:arena.performanceRanking.findIndex(item=>item.strategyId===entry.strategyId)+1}));anchorResults.push({anchor,summaries,researchRunId:response.record.researchRunId,cacheStatus:response.source==="MEMORY_HIT"||response.source==="STORE_HIT"?"HIT":response.source==="COMPUTED"?"MISS":"IN_FLIGHT_REUSED",durationMs:performance.now()-started})}return{anchors,anchorResults,leaderboard:aggregateAnchorResults(anchorResults)}}
export function validateResearchExport(value:unknown):boolean{if(isStoredResearchRecord(value))return true;if(!value||typeof value!=="object")return false;const record=value as{schemaVersion?:unknown;manifest?:{researchRunId?:unknown};researchRunId?:unknown;resultFingerprint?:unknown;result?:unknown};return record.schemaVersion==="veyrix-cache-v1"&&record.researchRunId===record.manifest?.researchRunId&&record.resultFingerprint===fingerprintResult(record.result)}
export const researchConfigurationCanonical=(timeframe:"180D"|"365D",anchor:string)=>canonicalize(researchConfiguration(timeframe,anchor));
export const configuredResearchStore=():ResearchStore|null=>configuredStore;
