import { mkdir, readFile, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fingerprintResult } from "./researchIdentity.ts";
import type { StoredResearchRecord } from "@/types/research";

export const RESEARCH_STORE_SCHEMA_VERSION="veyrix-store-v1",RESEARCH_HISTORY_LIMIT=25,RESEARCH_NOTE_MAX_LENGTH=160;
export interface ResearchStore{readonly name:string;readonly durable:boolean;readonly supportsPinning:boolean;get<T>(runId:string):Promise<StoredResearchRecord<T>|null>;put<T>(record:StoredResearchRecord<T>):Promise<void>;delete(runId:string):Promise<void>;has(runId:string):Promise<boolean>;list(limit?:number):Promise<StoredResearchRecord[]>}
const finite=(value:unknown):value is number=>typeof value==="number"&&Number.isFinite(value);
export function validateResearchNote(value:unknown):string|null{if(value===null||value===undefined||value==="")return null;if(typeof value!=="string")throw new Error("Research note must be text");const normalized=value.trim();if(!normalized||normalized.length>RESEARCH_NOTE_MAX_LENGTH)throw new Error(`Research note must be 1-${RESEARCH_NOTE_MAX_LENGTH} characters`);return normalized}
export function isStoredResearchRecord(value:unknown):value is StoredResearchRecord{if(!value||typeof value!=="object")return false;const record=value as Partial<StoredResearchRecord>;return record.schemaVersion===RESEARCH_STORE_SCHEMA_VERSION&&typeof record.researchRunId==="string"&&record.researchRunId.startsWith("VRX-")&&record.manifest?.researchRunId===record.researchRunId&&record.datasetFingerprint===record.manifest?.datasetFingerprint&&typeof record.resultFingerprint==="string"&&record.resultFingerprint===fingerprintResult(record.detailedResult)&&record.compactSummary?.researchRunId===record.researchRunId&&record.compactSummary?.datasetFingerprintPrefix===record.datasetFingerprint.slice(0,12)&&record.compactSummary?.resultFingerprintPrefix===record.resultFingerprint.slice(0,12)&&typeof record.createdAt==="string"&&Number.isFinite(Date.parse(record.createdAt))&&typeof record.expiresAt==="string"&&Number.isFinite(Date.parse(record.expiresAt))&&finite(record.sizes?.summaryBytes)&&finite(record.sizes?.detailedBytes)&&finite(record.sizes?.storedRecordBytes)&&record.sizes!.summaryBytes>=0&&record.sizes!.detailedBytes>=0&&record.sizes!.storedRecordBytes>=0&&typeof record.pinned==="boolean"&&(record.note===null||(typeof record.note==="string"&&record.note.length<=RESEARCH_NOTE_MAX_LENGTH))}
export class MemoryResearchStore implements ResearchStore{readonly name="memory";readonly durable=false;readonly supportsPinning=false;private records=new Map<string,StoredResearchRecord>();private trusted=new WeakSet<object>();async get<T>(id:string){const value=this.records.get(id);return value&&(this.trusted.has(value)||isStoredResearchRecord(value))?value as StoredResearchRecord<T>:null}async put<T>(record:StoredResearchRecord<T>){if(!isStoredResearchRecord(record))throw new Error("Invalid research record");this.records.set(record.researchRunId,record);this.trusted.add(record)}async delete(id:string){this.records.delete(id)}async has(id:string){return!!await this.get(id)}async list(limit=RESEARCH_HISTORY_LIMIT){return[...this.records.values()].filter(value=>this.trusted.has(value)||isStoredResearchRecord(value)).sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,Math.max(0,Math.min(limit,RESEARCH_HISTORY_LIMIT)))}clear(){this.records.clear();this.trusted=new WeakSet()}unsafeSet(id:string,value:unknown){this.records.set(id,value as StoredResearchRecord)}}
export class FileSystemResearchStore implements ResearchStore{readonly name="filesystem";readonly durable=true;readonly supportsPinning=true;private directory:string;constructor(directory=join(process.cwd(),".veyrix-research")){this.directory=directory}private path(id:string){return join(this.directory,`${id}.json`)}async get<T>(id:string){try{const parsed:unknown=JSON.parse(await readFile(this.path(id),"utf8"));return isStoredResearchRecord(parsed)?parsed as StoredResearchRecord<T>:null}catch{return null}}async put<T>(record:StoredResearchRecord<T>){if(!isStoredResearchRecord(record))throw new Error("Invalid research record");await mkdir(this.directory,{recursive:true});await writeFile(this.path(record.researchRunId),JSON.stringify(record),"utf8")}async delete(id:string){try{await unlink(this.path(id))}catch{}}async has(id:string){return!!await this.get(id)}async list(limit=RESEARCH_HISTORY_LIMIT){try{const names=(await readdir(this.directory)).filter(name=>/^VRX-[a-f0-9]+\.json$/.test(name)),records=(await Promise.all(names.map(name=>this.get(name.slice(0,-5))))).filter((value):value is StoredResearchRecord=>value!==null);return records.sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)).slice(0,Math.max(0,Math.min(limit,RESEARCH_HISTORY_LIMIT)))}catch{return[]}}}
