import assert from "node:assert/strict";
import test from "node:test";
import { calculatePerformanceAnalytics } from "./performanceAnalytics.ts";
const trade = (id, pnl, entryHour, exitHour, size = 1000) => ({ id, status: "CLOSED", entryTimestamp: new Date(Date.UTC(2026,0,1,entryHour)).toISOString(), exitTimestamp: new Date(Date.UTC(2026,0,1,exitHour)).toISOString(), positionSizeUsdc: size, realizedPnl: pnl });
const analytics = (trades, value = 10000 + trades.reduce((sum,t) => sum + (t.realizedPnl ?? 0), 0)) => calculatePerformanceAnalytics({ startingBalance: 10000, currentPortfolioValue: value, unrealizedPnl: 0, trades });
test("total return calculation",()=>assert.equal(analytics([trade("a",500,0,1)]).totalReturnPercent,5));
test("win rate calculation",()=>assert.equal(analytics([trade("a",10,0,1),trade("b",-5,2,3)]).winRate,50));
test("average winner calculation",()=>assert.equal(analytics([trade("a",10,0,1),trade("b",30,2,3)]).averageWinningTrade,20));
test("average loser calculation",()=>assert.equal(analytics([trade("a",-10,0,1),trade("b",-30,2,3)]).averageLosingTrade,-20));
test("profit factor",()=>assert.equal(analytics([trade("a",40,0,1),trade("b",-20,2,3)]).profitFactor,2));
test("profit factor with no losses is unavailable",()=>assert.equal(analytics([trade("a",40,0,1)]).profitFactor,null));
test("expectancy dollars and percent",()=>{const value=analytics([trade("a",100,0,1),trade("b",-50,2,3)]);assert.equal(value.expectancyDollars,25);assert.equal(value.expectancyPercent,2.5)});
test("equity curve is chronological and cumulative",()=>assert.deepEqual(analytics([trade("b",-20,2,3),trade("a",50,0,1)]).equityCurve.map(p=>p.equity),[10000,10050,10030]));
test("maximum drawdown",()=>assert.equal(analytics([trade("a",100,0,1),trade("b",-50,2,3),trade("c",-100,4,5)]).maximumDrawdownDollars,150));
test("winning streak",()=>assert.equal(analytics([trade("a",1,0,1),trade("b",2,2,3),trade("c",-1,4,5)]).longestWinningStreak,2));
test("losing streak and break-even reset",()=>{const value=analytics([trade("a",-1,0,1),trade("b",-2,2,3),trade("c",0,4,5),trade("d",-3,6,7)]);assert.equal(value.longestLosingStreak,2);assert.equal(value.currentLosingStreak,1)});
test("holding durations",()=>{const value=analytics([trade("a",1,0,1),trade("b",1,2,4)]);assert.equal(value.averageHoldingDurationMs,5400000);assert.equal(value.shortestHoldingDurationMs,3600000);assert.equal(value.longestHoldingDurationMs,7200000)});
test("empty trade history reports unavailable trade statistics",()=>{const value=analytics([]);assert.equal(value.completedTrades,0);assert.equal(value.winRate,null);assert.equal(value.profitFactor,null);assert.equal(value.equityCurve.length,1)});
test("malformed trades fail safely",()=>{const value=calculatePerformanceAnalytics({startingBalance:Number.NaN,currentPortfolioValue:Number.POSITIVE_INFINITY,unrealizedPnl:Number.NaN,trades:[null,{status:"CLOSED",realizedPnl:Number.NaN,exitTimestamp:"bad"}]});assert.equal(value.completedTrades,0);Object.values(value).filter(v=>typeof v==="number").forEach(v=>assert.ok(Number.isFinite(v)))});
