import type{BacktestConfig,BacktestResult,HistoricalCandle,HistoricalDataQuality}from"./backtesting";import type{MarketRegime,MultiRegimeReport,ParameterDriftReport,RegimeClassification,ReliabilityLabel}from"./multiRegime";import type{OverfittingRisk,SensitivityRun}from"./robustness";import type{StrategyId}from"./strategy";
export type ValidationMethod="ROLLING_OVERLAPPING"|"NON_OVERLAPPING"|"EXPANDING_WALK_FORWARD";
export type ValidationConfidence="LOW"|"MODERATE"|"HIGHER"|"UNAVAILABLE";
export interface ValidationFoldDefinition{index:number;training:readonly HistoricalCandle[];embargo:readonly HistoricalCandle[];test:readonly HistoricalCandle[];trainingStart:string;trainingEnd:string;testStart:string;testEnd:string}
export interface ExposureAnalytics{longPercent:number;flatPercent:number;averageCapitalDeployedUsd:number;maximumCapitalDeployedUsd:number;averageExposurePercent:number;returnPerTenPercentExposure:number|null}
export interface LossAttribution{byExitReason:{STOP_LOSS:number;STRATEGY_SIGNAL:number;TAKE_PROFIT:number};feesPaidUsd:number;estimatedSlippageCostUsd:number;totalLosingTrades:number;averageLosingTradeUsd:number|null;costShareOfLossPercent:number|null}
export interface ValidationFoldResult{index:number;trainingStart:string;trainingEnd:string;testStart:string;testEnd:string;embargoCandles:number;regime:RegimeClassification;selectedParameters:Record<string,number>|null;inSample:SensitivityRun|null;outOfSample:BacktestResult|null;outOfSampleScore:number|null;parameterStability:number|null;robustnessScore:number|null;overfittingRisk:OverfittingRisk;exposure:ExposureAnalytics;lossAttribution:LossAttribution}
export interface ValidationMethodMetrics{method:ValidationMethod;folds:ValidationFoldResult[];numberOfFolds:number;profitableFoldPercent:number|null;averageOutOfSampleReturnPercent:number|null;medianOutOfSampleReturnPercent:number|null;worstOutOfSampleReturnPercent:number|null;averageVeyrixScore:number|null;matchedBenchmarkBeatRatePercent:number|null;fullBenchmarkBeatRatePercent:number|null;averageMaximumDrawdownPercent:number|null;returnStandardDeviation:number|null;highOverfittingFoldPercent:number|null;averageRobustnessScore:number|null;averageMarketExposurePercent:number|null}
export interface RegimeDuration{regime:Exclude<MarketRegime,"UNAVAILABLE">;startTimestamp:string;endTimestamp:string;durationCandles:number;durationDays:number;marketReturnPercent:number;volatilityPercent:number;numberOfTrades:number;strategyReturnPercent:number;benchmarkReturnPercent:number}
export interface RegimeTransition{from:Exclude<MarketRegime,"UNAVAILABLE">;to:Exclude<MarketRegime,"UNAVAILABLE">;timestamp:string;strategyReturnPercent:number;tradeCount:number;profitable:boolean}
export interface TransitionSummary{transition:string;observations:number;averageStrategyReturnPercent:number|null;tradeCount:number;profitablePercent:number|null}
export interface FailureFold{dates:string;regime:MarketRegime;marketReturnPercent:number|null;selectedParameters:Record<string,number>|null;strategyReturnPercent:number;matchedBenchmarkReturnPercent:number;maximumDrawdownPercent:number;trades:number;losingTrades:number;exitReasons:Record<string,number>;parameterStability:number|null;overfittingRisk:OverfittingRisk;explanations:string[];lossAttribution:LossAttribution;exposure:ExposureAnalytics}
export interface ExtendedValidationReport{strategyId:StrategyId;strategyName:string;historyDays:number;methods:ValidationMethodMetrics[];validationAgreementScore:number|null;multiRegime:MultiRegimeReport;regimeDurations:RegimeDuration[];transitions:RegimeTransition[];transitionSummaries:TransitionSummary[];worstFolds:FailureFold[];researchScore:number|null;validationConfidence:ValidationConfidence;reliability:ReliabilityLabel;dataQuality:HistoricalDataQuality;averageProfitableFoldPercent:number|null;averageMatchedBeatRatePercent:number|null;averageExposurePercent:number|null;parameterDrift:ParameterDriftReport}
export interface ExtendedValidationArena{entries:ExtendedValidationReport[];performanceRanking:ExtendedValidationReport[];robustnessRanking:ExtendedValidationReport[];researchRanking:ExtendedValidationReport[]}
export interface ExtendedValidationInput{candles:readonly HistoricalCandle[];strategyId:StrategyId;config:Readonly<BacktestConfig>;historyDays:number;dataQuality:HistoricalDataQuality}
