import type{BacktestConfig,HistoricalCandle}from"./backtesting";import type{OverfittingRisk,WalkForwardReport}from"./robustness";import type{StrategyId}from"./strategy";
export type MarketRegime="BULLISH"|"BEARISH"|"SIDEWAYS"|"HIGH_VOLATILITY"|"UNAVAILABLE";
export type ReliabilityLabel="STRONG"|"PROMISING"|"MIXED"|"WEAK"|"UNAVAILABLE";
export type ParameterDrift="LOW"|"MODERATE"|"HIGH"|"UNAVAILABLE";
export interface RegimeClassification{regime:MarketRegime;marketReturnPercent:number|null;realizedVolatilityPercent:number|null;trendDeviationPercent:number|null}
export interface RollingWindow{index:number;startTimestamp:string;endTimestamp:string;candles:readonly HistoricalCandle[]}
export interface RollingWindowResult{index:number;startTimestamp:string;endTimestamp:string;regime:MarketRegime;marketReturnPercent:number|null;realizedVolatilityPercent:number|null;trendDeviationPercent:number|null;walkForward:WalkForwardReport;selectedParameters:Record<string,number>|null;inSampleReturnPercent:number|null;outOfSampleReturnPercent:number|null;outOfSampleVeyrixScore:number|null;parameterStability:number|null;robustnessScore:number|null;overfittingRisk:OverfittingRisk;fullBenchmarkReturnPercent:number|null;matchedBenchmarkReturnPercent:number|null}
export interface RegimeAggregate{regime:Exclude<MarketRegime,"UNAVAILABLE">;windows:number;averageOutOfSampleReturnPercent:number|null;profitableWindowPercent:number|null;averageRobustnessScore:number|null}
export interface ParameterDriftReport{mostFrequentParameters:Record<string,number>|null;uniqueConfigurations:number;modalConfigurationPercent:number|null;consecutiveChanges:number;changePercent:number|null;temporalStability:number|null;classification:ParameterDrift}
export interface CrossWindowAnalytics{numberOfWindows:number;profitableWindows:number;losingWindows:number;profitableWindowPercent:number|null;averageOutOfSampleReturnPercent:number|null;medianOutOfSampleReturnPercent:number|null;bestOutOfSampleReturnPercent:number|null;worstOutOfSampleReturnPercent:number|null;averageOutOfSampleVeyrixScore:number|null;averageRobustnessScore:number|null;averageParameterStability:number|null;highOverfittingWindows:number;maximumOutOfSampleDrawdownPercent:number|null;standardDeviationOutOfSampleReturns:number|null;matchedBenchmarkBeatRatePercent:number|null;fullBenchmarkBeatRatePercent:number|null;crossWindowConsistency:number|null}
export interface MultiRegimeReport{strategyId:StrategyId;strategyName:string;historyDays:number;windows:RollingWindowResult[];analytics:CrossWindowAnalytics;regimes:RegimeAggregate[];parameterDrift:ParameterDriftReport;acceptableRegimePercent:number|null;multiRegimeRobustnessScore:number|null;reliability:ReliabilityLabel}
export interface MultiRegimeArena{entries:MultiRegimeReport[];ranked:MultiRegimeReport[];historyDays:number;candleCount:number}
export interface MultiRegimeInput{candles:readonly HistoricalCandle[];strategyId:StrategyId;config:Readonly<BacktestConfig>;historyDays:number}
