import assert from "node:assert/strict";
import test from "node:test";
import { runBacktest } from "./backtestEngine.ts";
import { evaluateMomentum } from "../strategy/momentumStrategy.ts";
import { createInitialPaperPortfolio } from "../trading/paperPortfolio.ts";
const strategy={minimumObservations:2,lookbackObservations:2,momentumThresholdPercent:.1,averageDeviationThresholdPercent:.04,minimumMovementPercent:.01};
const paper={startingBalanceUsd:10000,positionSizePercent:10,maxOpenPositions:1,allowShortSelling:false,allowLeverage:false,stopLossPercent:2,takeProfitPercent:4,maxDailyLossPercent:3};
const config={strategy,paperTrading:paper,risk:paper};
const obs=(prices)=>prices.map((price,i)=>({timestamp:new Date(Date.UTC(2026,0,1,i)).toISOString(),price}));
test("rising historical series can produce a BUY",()=>assert.equal(runBacktest(obs([100,101]),config).openPosition,true));
test("falling conditions produce a SELL signal",()=>assert.equal(evaluateMomentum(obs([101,100]),strategy).signal,"SELL"));
test("backtest does not modify live portfolio state",()=>{const live=createInitialPaperPortfolio("2026-01-01"),snapshot=structuredClone(live);runBacktest(obs([100,101,102]),config);assert.deepEqual(live,snapshot)});
test("stop loss works in backtesting",()=>assert.equal(runBacktest(obs([100,101,98]),config).trades[0].exitReason,"STOP_LOSS"));
test("take profit works in backtesting",()=>assert.equal(runBacktest(obs([100,101,106]),config).trades[0].exitReason,"TAKE_PROFIT"));
test("strategy exit works in backtesting",()=>assert.equal(runBacktest(obs([100,101,100.5]),config).trades[0].exitReason,"STRATEGY_SIGNAL"));
test("duplicate timestamps are handled safely",()=>{const input=[...obs([100,101]),{...obs([102])[0],price:999}];const result=runBacktest(input,config);assert.equal(result.ignoredObservations,1);assert.equal(result.processedObservations,2)});
test("invalid prices are ignored safely",()=>{const result=runBacktest([...obs([100,101]),{timestamp:"bad",price:-1}],config);assert.equal(result.ignoredObservations,1)});
test("final equity is calculated correctly",()=>assert.equal(runBacktest(obs([100,101,106]),config).finalBalance,10049.504950495049));
test("backtest metrics match generated trades",()=>{const result=runBacktest(obs([100,101,106]),config);assert.equal(result.analytics.completedTrades,1);assert.equal(result.analytics.realizedPnl,result.trades[0].realizedPnl)});
test("no short positions are created",()=>assert.equal(runBacktest(obs([101,100,99]),config).trades.length,0));
test("portfolio balances stay finite and non-negative",()=>{const result=runBacktest(obs([100,101,98,100,102,107]),config);[result.finalBalance,result.finalCashBalance,result.finalPositionValue].forEach(v=>assert.ok(Number.isFinite(v)&&v>=0))});
