"use client";
import { useMemo, useState } from "react";
import { EquityCurveChart } from "./EquityCurveChart";
import { MARKET_IDS, MARKET_REGISTRY, type MarketId } from "@/lib/market/marketRegistry";
import { LIVE_TIMEFRAME_IDS } from "@/lib/market/liveCandles";
import { strategyList } from "@/lib/strategy/strategyRegistry";
import { defaultAgentName, MAX_ACTIVE_AGENTS, MAX_SAVED_AGENTS, STRATEGY_LABELS } from "@/lib/agents/agentModel";
import { allAgentProfiles, aggregateAgentPerformance, calculateAgentPerformance } from "@/lib/agents/agentPerformance";
import type { AgentConfig, PaperLabState } from "@/types/agents";
import type { StrategyId } from "@/types/strategy";
import { unifiedTradeHistory } from "@/lib/trading/tradeHistory";

const usd=(n:number)=>`${n<0?"−":""}$${Math.abs(n).toFixed(2)}`;
function emptyConfig(): AgentConfig { const c={name:"",marketId:"BTC" as MarketId,mode:"SPOT" as const,strategyId:"momentum" as StrategyId,timeframe:"15m" as const,allocation:{unit:"USDC" as const,value:1000},stopLossPercent:3,takeProfitPercent:6,leverage:1 as const};c.name=defaultAgentName(c);return c; }
export function AgentDashboard({state,prices,controllerAvailable,error,onCreate,onEdit,onToggle,onDelete,onReset}:{state:PaperLabState;prices:Partial<Record<MarketId,number>>;controllerAvailable:boolean;error:string|null;onCreate(c:AgentConfig):void;onEdit(id:string,c:AgentConfig):void;onToggle(id:string,enabled:boolean):void;onDelete(id:string,leave:boolean):void;onReset():void}){
  const [config,setConfig]=useState<AgentConfig>(emptyConfig),[creating,setCreating]=useState(false),[editing,setEditing]=useState<string|null>(null),[detailId,setDetailId]=useState<string|null>(null),[chartAgent,setChartAgent]=useState("ALL"),[formError,setFormError]=useState<string|null>(null);
 const summary=aggregateAgentPerformance(state,prices),profiles=allAgentProfiles(state),detail=profiles.find(a=>a.id===detailId),metrics=detail?calculateAgentPerformance(detail.id,state,prices):null,detailTrades=detail?unifiedTradeHistory(state.portfolio).filter(t=>"agentId" in t&&t.agentId===detail.id).slice(0,5):[];
 const curve=useMemo(()=>chartAgent==="ALL"?[]:calculateAgentPerformance(chartAgent,state,prices).equityCurve,[chartAgent,state,prices]);
 const beginEdit=(id:string)=>{const a=state.agents.agents.find(x=>x.id===id);if(a){setConfig({...a,allocation:{...a.allocation}});setEditing(id);setCreating(true)}};
 const select=(key:string,value:string)=>setConfig(c=>({...c,...(key==="allocation.unit"?{allocation:{unit:value as "USDC"|"PERCENT",value:c.allocation.unit===value?c.allocation.value:value==="USDC"?1000:10}}:key==="allocation.value"?{allocation:{...c.allocation,value:Number(value)}}:key==="marketId"?{marketId:value as MarketId,name:defaultAgentName({...c,marketId:value as MarketId})}:key==="mode"?{mode:value as AgentConfig["mode"],leverage:value==="SPOT"?1:c.leverage,name:defaultAgentName({...c,mode:value as AgentConfig["mode"]})}:key==="strategyId"?{strategyId:value as StrategyId,name:defaultAgentName({...c,strategyId:value as StrategyId})}:key==="timeframe"?{timeframe:value as AgentConfig["timeframe"]}:key==="leverage"?{leverage:Number(value) as AgentConfig["leverage"]}:key==="stopLossPercent"?{stopLossPercent:Number(value)}:key==="takeProfitPercent"?{takeProfitPercent:Number(value)}:{name:value})}));
 const submit=()=>{try{if(editing)onEdit(editing,config);else onCreate(config);setCreating(false);setEditing(null);setFormError(null);setConfig(emptyConfig())}catch(e){setFormError(e instanceof Error?e.message:"Invalid agent configuration.")}};
 const askDelete=(id:string,hasPosition:boolean)=>{if(hasPosition){if(confirm("This agent owns an open paper position. Delete the agent and leave the position open under manual control?"))onDelete(id,true)}else if(confirm("Delete this paused paper agent? Its completed history will remain available."))onDelete(id,false)};
 return <section className="agent-dashboard" aria-label="Automation agents">
  <div className="section-heading"><div><span>SIMULATED CLOSED-CANDLE EXECUTION</span><h2>AUTOMATION AGENTS</h2></div><div className="agent-actions"><span>{summary.activeAgents}/{MAX_ACTIVE_AGENTS} running</span><button disabled={!controllerAvailable||state.agents.agents.length>=MAX_SAVED_AGENTS} onClick={()=>{setEditing(null);setFormError(null);setConfig(emptyConfig());setCreating(v=>!v)}}>CREATE AGENT</button></div></div>
  {!controllerAvailable&&<p role="status">Another browser tab currently controls this local paper account. This tab is read-only.</p>}{error&&<p role="alert">{error}</p>}
  {creating&&<div className="panel agent-form"><h3>{editing?"EDIT AGENT":"CREATE AGENT"}</h3><label>Agent name<input maxLength={32} value={config.name} onChange={e=>select("name",e.target.value)}/></label><label>Market<select value={config.marketId} onChange={e=>select("marketId",e.target.value)}>{MARKET_IDS.map(id=><option key={id} value={id}>{MARKET_REGISTRY[id].displaySymbol}</option>)}</select></label><label>Trading mode<select value={config.mode} onChange={e=>select("mode",e.target.value)}><option value="SPOT">SPOT PAPER</option><option value="FUTURES">FUTURES PAPER</option></select></label><label>Strategy<select value={config.strategyId} onChange={e=>select("strategyId",e.target.value)}>{strategyList.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Timeframe<select value={config.timeframe} onChange={e=>select("timeframe",e.target.value)}>{LIVE_TIMEFRAME_IDS.map(t=><option key={t}>{t}</option>)}</select></label><label>Allocation unit<select value={config.allocation.unit} onChange={e=>select("allocation.unit",e.target.value)}><option value="USDC">Virtual USDC</option><option value="PERCENT">% of available USDC</option></select></label><label>Allocation {config.allocation.unit==="USDC"?"(virtual USDC)":"(percent)"}<input aria-label="Allocation amount" type="number" min="0.01" max={config.allocation.unit==="PERCENT"?100:10000} step="any" value={config.allocation.value} onChange={e=>select("allocation.value",e.target.value)}/></label><label>Stop loss % (0 disables)<input type="number" min="0" max="99.99" value={config.stopLossPercent} onChange={e=>select("stopLossPercent",e.target.value)}/></label><label>Take profit % (0 disables)<input type="number" min="0" max="99.99" value={config.takeProfitPercent} onChange={e=>select("takeProfitPercent",e.target.value)}/></label>{config.mode==="FUTURES"&&<label>Simulated leverage<select value={config.leverage} onChange={e=>select("leverage",e.target.value)}>{[1,2,3,5].map(n=><option key={n} value={n}>{n}x</option>)}</select></label>}<button disabled={!controllerAvailable} onClick={submit}>{editing?"SAVE EDIT":"CREATE PAUSED AGENT"}</button><button onClick={()=>{setCreating(false);setEditing(null)}}>CANCEL</button>{formError&&<p role="alert">{formError}</p>}</div>}
  {!state.agents.agents.length&&<div className="panel"><p>No automation agents yet.</p><p>Create an agent to run paper strategies across BTC, ETH, or SOL.</p><button disabled={!controllerAvailable} onClick={()=>setCreating(true)}>CREATE AGENT</button></div>}
  <div className="agent-grid">{state.agents.agents.map(agent=>{const p=calculateAgentPerformance(agent.id,state,prices),position=agent.mode==="SPOT"?state.portfolio.spotPositions?.[agent.marketId]?.agentId===agent.id?state.portfolio.spotPositions[agent.marketId]:null:(state.portfolio.futuresTrades??[]).find(t=>t.status==="OPEN"&&t.agentId===agent.id),positionLabel=!position?"FLAT":agent.mode==="SPOT"&&"quantity" in position?`${position.quantity.toPrecision(5)} ${agent.marketId}`:"side" in position?`${position.side} ${position.leverage}x`:"FLAT";const isOpen=Boolean(position);return <article className="panel agent-card" key={agent.id}><div className="agent-card-heading"><div><h3>{agent.name}</h3><span>{MARKET_REGISTRY[agent.marketId].displaySymbol} · {agent.mode==="SPOT"?"SPOT PAPER":"FUTURES PAPER"}{agent.mode==="FUTURES"?` ${agent.leverage}x`:""}</span></div><strong className={`agent-status ${agent.enabled?"active":"paused"}`}>{agent.enabled?"RUNNING":"PAUSED"}</strong></div><p>{STRATEGY_LABELS[agent.strategyId]} · {agent.timeframe} · {agent.allocation.unit==="USDC"?usd(agent.allocation.value):`${agent.allocation.value}% available`}</p><dl><div><dt>Position</dt><dd>{positionLabel}</dd></div><div><dt>Last signal</dt><dd>{agent.lastSignal??"—"}</dd></div><div><dt>Last action</dt><dd>{agent.lastAction}</dd></div><div><dt>Realized / unrealized</dt><dd>{usd(p.netRealizedPnl)} / {usd(p.unrealizedPnl)}</dd></div><div><dt>Trades / win rate</dt><dd>{p.completedTrades} / {p.winRate===null?"—":`${p.winRate.toFixed(1)}%`}</dd></div><div><dt>Veyrix Agent Score</dt><dd>{p.score??p.scoreStatus}</dd></div></dl><div className="agent-card-actions"><button disabled={!controllerAvailable||editing===agent.id||(!agent.enabled&&summary.activeAgents>=MAX_ACTIVE_AGENTS)} onClick={()=>onToggle(agent.id,!agent.enabled)}>{agent.enabled?"PAUSE":"START"}</button><button disabled={!controllerAvailable} onClick={()=>beginEdit(agent.id)}>EDIT</button><button onClick={()=>setDetailId(agent.id)}>VIEW DETAILS</button><a href={`/research?market=${agent.marketId}&strategy=${agent.strategyId}&timeframe=${agent.timeframe}`}>RESEARCH THIS STRATEGY</a><button disabled={!controllerAvailable} onClick={()=>askDelete(agent.id,isOpen)}>DELETE</button></div></article>})}</div>
  <section className="panel agent-comparison"><h3>COMPARE AGENTS</h3><p>Each row reports its observed paper-trade figures; no ranking predicts future performance.</p><div className="table-wrap"><table><thead><tr>{["Agent","Market","Mode","Strategy","Trades","Win rate","Net P&L","Drawdown","Profit factor","Expectancy","Veyrix Agent Score"].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{profiles.map(a=>{const p=calculateAgentPerformance(a.id,state,prices);return <tr key={a.id}><td>{a.name}{a.deletedAt?" (deleted)":""}</td><td>{a.marketId}</td><td>{a.mode}</td><td>{STRATEGY_LABELS[a.strategyId]}</td><td>{p.completedTrades}</td><td>{p.winRate===null?"—":`${p.winRate.toFixed(1)}%`}</td><td>{usd(p.netRealizedPnl)}</td><td>{usd(p.maximumDrawdown)}</td><td>{p.profitFactor?.toFixed(2)??"—"}</td><td>{p.expectancy===null?"—":usd(p.expectancy)}</td><td>{p.score??"INSUFFICIENT DATA"}</td></tr>})}</tbody></table></div></section>
  <section className="panel agent-analytics"><h3>AGGREGATE AUTOMATION ANALYTICS</h3><div className="agent-kpis">{[["Active agents",String(summary.activeAgents)],["Autonomous trades",String(summary.totalAutonomousTrades)],["Combined realized P&L",usd(summary.combinedRealizedPnl)],["Combined unrealized P&L",usd(summary.combinedUnrealizedPnl)],["Best by net P&L",summary.bestAgent?.name??"Insufficient trade data"],["Worst drawdown",usd(summary.worstDrawdown)],["Capital deployed",usd(summary.capitalDeployed)]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><label>Equity curves<select value={chartAgent} onChange={e=>setChartAgent(e.target.value)}><option value="ALL">All agents</option>{profiles.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><p>Realized cumulative P&amp;L from zero, shown separately for each agent; curves are never combined.</p>{chartAgent==="ALL"?profiles.length?<div className="agent-grid">{profiles.map(a=><section className="agent-equity panel" key={a.id}><h4>{a.name}{a.deletedAt?" (deleted)":""}</h4><EquityCurveChart points={calculateAgentPerformance(a.id,state,prices).equityCurve} emptyMessage="No completed trades for this agent yet." primaryLabel={a.name}/></section>)}</div>:<div className="analytics-empty">No agents have equity history.</div>:<EquityCurveChart points={curve} emptyMessage="No completed trades for this agent yet." primaryLabel={detail?.name??"Agent"}/>}</section>
  {detail&&metrics&&<section className="panel agent-detail"><button onClick={()=>setDetailId(null)}>CLOSE DETAILS</button><h3>{detail.name} · CONFIGURATION AND PERFORMANCE</h3><p>{detail.marketId}/USDC · {detail.mode} · {STRATEGY_LABELS[detail.strategyId]} · {detail.timeframe} · allocation {detail.allocation.value} {detail.allocation.unit}</p><p>Stop {detail.stopLossPercent}% · target {detail.takeProfitPercent}% · leverage {detail.leverage}x · processed candles {detail.processedCandleIds.length}</p><p>Trades {metrics.totalTrades} / completed {metrics.completedTrades} · wins {metrics.winningTrades} · losses {metrics.losingTrades} · gross profit {usd(metrics.grossProfit)} · gross loss {usd(metrics.grossLoss)} · average win {metrics.averageWin===null?"—":usd(metrics.averageWin)} · average loss {metrics.averageLoss===null?"—":usd(metrics.averageLoss)} · largest win {metrics.largestWin===null?"—":usd(metrics.largestWin)} · largest loss {metrics.largestLoss===null?"—":usd(metrics.largestLoss)} · profit factor {metrics.profitFactor?.toFixed(2)??"—"} · expectancy {metrics.expectancy===null?"—":usd(metrics.expectancy)} · current streak {metrics.currentWinLossStreak} · average holding {metrics.averageHoldingTimeMs===null?"—":`${(metrics.averageHoldingTimeMs/3600000).toFixed(1)} h`} · return on allocated capital {metrics.returnOnAllocatedCapital===null?"—":`${metrics.returnOnAllocatedCapital.toFixed(2)}%`} · return on futures margin {metrics.returnOnMargin===null?"—":`${metrics.returnOnMargin.toFixed(2)}%`}</p><p>Current position: {detail.mode==="SPOT"?state.portfolio.spotPositions?.[detail.marketId]?.agentId===detail.id?`${state.portfolio.spotPositions[detail.marketId]?.quantity.toPrecision(5)} ${detail.marketId}`:"FLAT":(state.portfolio.futuresTrades??[]).find(t=>t.status==="OPEN"&&t.agentId===detail.id)?.side??"FLAT"}</p><EquityCurveChart points={metrics.equityCurve} emptyMessage="No completed trades for this agent yet." primaryLabel={detail.name}/><h4>Recent trades</h4><ol>{detailTrades.map(t=><li key={t.id}>{t.marketId} {t.mode} · {t.status} · {t.exitTimestamp??t.entryTimestamp} · {t.realizedPnl===null?"Open":usd(t.realizedPnl)}</li>)}</ol><h4>Recent signals and activity</h4><ol>{detail.recentEvents.slice().reverse().map((e,i)=><li key={`${e.candleId}-${i}`}>{e.timestamp} · {e.signal??"—"} · {e.action}</li>)}</ol></section>}
  <button disabled={!controllerAvailable} onClick={onReset}>RESET PAPER ACCOUNT</button>
  <small>Veyrix Agent Score = 25% allocated-capital return score + 25% drawdown score + 20% profit-factor score + 20% expectancy score + 10% trade-count sufficiency score. Each part is clamped to 0–100; at least 5 completed trades are required. The score summarizes past paper results; it does not predict returns.</small>
  <small>Agents run only while this browser tab is open. Paused agents do not enter or strategy-exit; position stops, targets, and liquidation remain monitored. On restart only the latest safe closed candle is evaluated. A deleted agent&apos;s open position remains open under manual control.</small>
 </section>
}
