"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase/browser";
export function AuthFormShell({ mode }: { mode: "login" | "signup" | "forgot" | "update" }) {
  const router = useRouter();
  const configured = Boolean(getBrowserSupabase()); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [name,setName]=useState(""); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setMessage(""); if (!configured) return setMessage("Account features are unavailable until Supabase is configured. Guest Mode remains fully available."); if (mode === "signup" && (!name.trim() || password.length < 8 || password !== confirm)) return setMessage("Enter a display name, use at least 8 characters, and make sure passwords match."); setBusy(true); const s=getBrowserSupabase()!; let error: { message?: string } | null=null; if(mode==="login") ({error}=await s.auth.signInWithPassword({email,password})); else if(mode==="signup") { const r=await s.auth.signUp({email,password,options:{data:{display_name:name.trim()},emailRedirectTo:`${window.location.origin}/auth/callback`}}); error=r.error; if(!error) return setMessage("Check your email to verify your Veyrix account."); } else if(mode==="forgot") { const r=await s.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/update-password`}); error=r.error; if(!error) return setMessage("If an account exists for this email, a recovery link has been sent."); } else { const r=await s.auth.updateUser({password}); error=r.error; if(!error) return setMessage("Password updated. You can return to the Dashboard."); } setBusy(false); setMessage(error?.message || "Request could not be completed."); if(mode==="login"&&!error) router.push("/"); };
  const title={login:"Log in",signup:"Create your account",forgot:"Recover your password",update:"Set a new password"}[mode]; return <main className="auth-page"><div className="auth-card"><p className="eyebrow">Veyrix account</p><h1>{title}</h1>{!configured&&<p className="notice">Guest Mode is active. Configure Supabase to enable accounts and cloud sync.</p>}<form onSubmit={submit}>{mode==="signup"&&<label>Display Name<input value={name} onChange={e=>setName(e.target.value)} /></label>}{mode!=="update"&&<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label>}{mode!=="forgot"&&<label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>}{(mode==="signup"||mode==="update")&&<label>Confirm Password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} required /></label>}<button className="primary-button" disabled={busy}>{busy?"Working…":mode==="login"?"Log In":mode==="signup"?"Create Account":mode==="forgot"?"Send Recovery Link":"Update Password"}</button></form>{message&&<p className="form-message" role="status">{message}</p>}<p className="auth-links">{mode!=="login"&&<Link href="/auth/login">Log in</Link>} {mode!=="signup"&&<Link href="/auth/sign-up">Create account</Link>} {mode==="login"&&<Link href="/auth/forgot-password">Forgot password?</Link>}<Link href="/">Back to Dashboard</Link></p></div></main>;
}
