import { automationCandleId,closedCandles,nextCandleClose } from "../market/liveCandles.ts";
import { getStrategy } from "../strategy/strategyRegistry.ts";
import { closeFuturesMarket,openFutures } from "./futuresEngine.ts";
import { closeMarketSpot,openMarketSpot } from "./multiMarketSpotEngine.ts";
import type { HistoricalCandle } from "@/types/backtesting";
import type { AutomationSettings,AutomationStatus } from "@/types/liveTrading";
import type { PaperPortfolioState } from "@/types/trading";
export function evaluateMultiMarketAutomation(input:{portfolio:PaperPortfolioState;settings:AutomationSettings;candles:readonly HistoricalCandle[];now?:number}){
 const now=input.now??Date.now(),marketId=input.settings.marketId??"SOL",mode=input.settings.tradingMode??"SPOT",available=closedCandles(input.candles,input.settings.timeframe,now),latest=available.at(-1),baseStatus:AutomationStatus={signal:null,lastEvaluatedCandle:null,lastEvaluationTime:null,lastExecution:null,nextExpectedClose:nextCandleClose(input.settings.timeframe,now)};
 if(!input.settings.enabled)return{portfolio:input.portfolio,settings:input.settings,status:baseStatus,outcome:"DISABLED" as const};
 if(!latest)return{portfolio:input.portfolio,settings:input.settings,status:baseStatus,outcome:"NO_CLOSED_CANDLE" as const};
 const id=automationCandleId(input.settings.strategyId,input.settings.timeframe,latest.timestamp,marketId,mode);if(input.settings.processedCandleIds.includes(id)||(marketId==="SOL"&&mode==="SPOT"&&input.settings.processedCandleIds.includes(automationCandleId(input.settings.strategyId,input.settings.timeframe,latest.timestamp))))return{portfolio:input.portfolio,settings:input.settings,status:{...baseStatus,lastEvaluatedCandle:latest.timestamp},outcome:"DUPLICATE" as const};
 const decision=getStrategy(input.settings.strategyId).evaluate(available.map(c=>({timestamp:c.timestamp,price:c.close}))),allocation=Math.min(input.portfolio.availableUsdc,input.portfolio.availableUsdc*(input.settings.allocationPercent??10)/100);let portfolio=input.portfolio,outcome:"EXECUTED"|"NO_ACTION"|"SKIPPED"="NO_ACTION";
 if(mode==="SPOT"){const open=input.portfolio.spotPositions?.[marketId];if(decision.signal==="BUY"&&!open){const result=openMarketSpot(input.portfolio,{marketId,amountUsdc:allocation,price:latest.close,source:"AUTONOMOUS",timestamp:latest.timestamp,stopLoss:input.settings.stopLossPercent===0?null:latest.close*(1-(input.settings.stopLossPercent??3)/100),takeProfit:input.settings.takeProfitPercent===0?null:latest.close*(1+(input.settings.takeProfitPercent??6)/100)});portfolio=result.portfolio;outcome=result.error?"SKIPPED":"EXECUTED"}else if(decision.signal==="SELL"&&open){portfolio=closeMarketSpot(input.portfolio,marketId,latest.close,latest.timestamp);outcome="EXECUTED"}}
 else {const open=(input.portfolio.futuresTrades??[]).find(t=>t.status==="OPEN"&&(t.marketId??"SOL")===marketId);if(!open&&decision.signal!=="HOLD"){const side=decision.signal==="BUY"?"LONG":"SHORT",sl=(input.settings.stopLossPercent??3)/100,tp=(input.settings.takeProfitPercent??6)/100,result=openFutures(input.portfolio,{marketId,side,leverage:input.settings.leverage??1,marginUsdc:allocation,price:latest.close,source:"AUTONOMOUS",timestamp:latest.timestamp,stopLoss:sl===0?null:side==="LONG"?latest.close*(1-sl):latest.close*(1+sl),takeProfit:tp===0?null:side==="LONG"?latest.close*(1+tp):latest.close*(1-tp)});portfolio=result.portfolio;outcome=result.error?"SKIPPED":"EXECUTED"}else if(open&&((open.side==="LONG"&&decision.signal==="SELL")||(open.side==="SHORT"&&decision.signal==="BUY"))){portfolio=closeFuturesMarket(input.portfolio,marketId,latest.close,latest.timestamp,true);outcome="EXECUTED"}}
 const settings={...input.settings,lastProcessedCandleId:id,processedCandleIds:[...input.settings.processedCandleIds,id].slice(-500)};return{portfolio,settings,status:{...baseStatus,signal:decision,lastEvaluatedCandle:latest.timestamp,lastEvaluationTime:new Date(now).toISOString(),lastExecution:outcome==="EXECUTED"?`${marketId} ${mode} ${decision.signal} @ $${latest.close.toFixed(2)}`:`${decision.signal} — ${outcome}`},outcome};
}
