import { evaluateMomentum,momentumStrategyConfig } from "../strategy/momentumStrategy.ts";import { evaluateMovingAverage,movingAverageConfig } from "../strategy/movingAverageStrategy.ts";import { evaluateMeanReversion,meanReversionConfig } from "../strategy/meanReversionStrategy.ts";
import type { StrategyDefinition,StrategyId } from "@/types/strategy";import type { StrategyParameterSchema } from "@/types/robustness";
const definition=(key:string,displayName:string,defaultValue:number,minimum:number,maximum:number,step:number,values:number[])=>({key,displayName,defaultValue,minimum,maximum,step,values});
const validValues=(schema:StrategyParameterSchema,values:Readonly<Record<string,number>>)=>schema.parameters.every(p=>Number.isFinite(values[p.key])&&values[p.key]>=p.minimum&&values[p.key]<=p.maximum&&p.values.includes(values[p.key]));
export const parameterSchemas:Readonly<Record<StrategyId,StrategyParameterSchema>>={
 momentum:{strategyId:"momentum",parameters:[definition("momentumThresholdPercent","Momentum threshold",.35,.2,.5,.15,[.2,.35,.5]),definition("averageDeviationThresholdPercent","Average deviation",.15,.1,.25,.05,[.1,.15,.25])],validate(values){return validValues(this,values)},createStrategy(values){const config={...momentumStrategyConfig,momentumThresholdPercent:values.momentumThresholdPercent,averageDeviationThresholdPercent:values.averageDeviationThresholdPercent};return{id:"momentum",name:"Momentum Agent",description:"Sensitivity configuration",minimumObservations:config.minimumObservations,maximumObservations:config.lookbackObservations,configuration:{...config},evaluate:obs=>{const r=evaluateMomentum(obs,config);return{...r,metrics:{...r.metrics}}}}}},
 moving_average:{strategyId:"moving_average",parameters:[definition("fastPeriod","Fast period",5,3,7,2,[3,5,7]),definition("slowPeriod","Slow period",12,9,15,3,[9,12,15])],validate(values){return validValues(this,values)&&values.fastPeriod<values.slowPeriod},createStrategy(values){const config={...movingAverageConfig,fastPeriod:values.fastPeriod,slowPeriod:values.slowPeriod};return{id:"moving_average",name:"Moving Average Agent",description:"Sensitivity configuration",minimumObservations:config.slowPeriod+1,maximumObservations:config.slowPeriod+1,configuration:{...config},evaluate:obs=>evaluateMovingAverage(obs,config)}}},
 mean_reversion:{strategyId:"mean_reversion",parameters:[definition("lookbackPeriod","Lookback period",12,8,16,4,[8,12,16]),definition("buyDeviationPercent","Buy deviation",-1,-1.25,-.75,.25,[-.75,-1,-1.25]),definition("sellDeviationPercent","Reversion threshold",0,-.1,0,.1,[-.1,0])],validate(values){return validValues(this,values)&&values.buyDeviationPercent<values.sellDeviationPercent},createStrategy(values){const config={...meanReversionConfig,lookbackPeriod:values.lookbackPeriod,buyDeviationPercent:values.buyDeviationPercent,sellDeviationPercent:values.sellDeviationPercent};return{id:"mean_reversion",name:"Mean Reversion Agent",description:"Sensitivity configuration",minimumObservations:config.lookbackPeriod,maximumObservations:config.lookbackPeriod,configuration:{...config},evaluate:obs=>evaluateMeanReversion(obs,config)}}},
};
export function defaultParameters(id:StrategyId):Record<string,number>{return Object.fromEntries(parameterSchemas[id].parameters.map(p=>[p.key,p.defaultValue]))}
export function generateParameterGrid(id:StrategyId):Record<string,number>[]{
 const schema=parameterSchemas[id];let combinations:Record<string,number>[]=[{}];for(const parameter of schema.parameters)combinations=combinations.flatMap(values=>parameter.values.map(value=>({...values,[parameter.key]:value})));return combinations.filter(values=>schema.validate(values));
}
export function createParameterizedStrategy(id:StrategyId,values:Readonly<Record<string,number>>):StrategyDefinition{const schema=parameterSchemas[id];if(!schema.validate(values))throw new Error("Invalid strategy parameters");return schema.createStrategy(values)}
