import { calculateVeyrixScore } from "../analytics/veyrixScore.ts";import { normalizeHistoricalCandles } from "../backtesting/marketCandles.ts";import { runBacktest } from "../backtesting/backtestEngine.ts";import { strategyList,strategyRegistry } from "../strategy/strategyRegistry.ts";import { createParameterizedStrategy } from "./parameterSchemas.ts";import { runParameterSensitivity } from "./parameterSensitivity.ts";
import type { BacktestConfig,HistoricalCandle } from "@/types/backtesting";import type { OverfittingRisk,RobustnessArenaResult,WalkForwardReport } from "@/types/robustness";import type { StrategyId } from "@/types/strategy";
export function splitWalkForward(candles:readonly HistoricalCandle[]){const sorted=normalizeHistoricalCandles(candles).candles,index=Math.floor(sorted.length*.7);return{splitIndex:index,inSample:sorted.slice(0,index),outOfSample:sorted.slice(index)}}
export function classifyOverfitting(stability:number,returnDecay:number,scoreDecay:number,inReturn:number,outReturn:number):OverfittingRisk{if(![stability,returnDecay,scoreDecay,inReturn,outReturn].every(Number.isFinite))return"UNAVAILABLE";if(stability<40||scoreDecay<-30||(inReturn>0&&outReturn<0&&returnDecay<-1))return"HIGH";if(stability<70||scoreDecay<-15||returnDecay<-.5)return"MODERATE";return"LOW"}
export function calculateRobustness(oosScore:number,stability:number,returnDecay:number,inDrawdown:number,outDrawdown:number):number|null{if(![oosScore,stability,returnDecay,inDrawdown,outDrawdown].every(Number.isFinite))return null;const returnConsistency=Math.max(0,100-Math.abs(returnDecay)*10),drawdownConsistency=Math.max(0,100-Math.max(0,outDrawdown-inDrawdown)*10);return Math.max(0,Math.min(100,oosScore*.4+stability*.25+returnConsistency*.2+drawdownConsistency*.15))}
export function runWalkForward(candles:readonly HistoricalCandle[],strategyId:StrategyId,config:Readonly<BacktestConfig>):WalkForwardReport{
 const normalized=normalizeHistoricalCandles(candles).candles,{splitIndex,inSample,outOfSample}=splitWalkForward(normalized),minimum=strategyRegistry[strategyId].minimumObservations,defaultThirtyDayResult=normalized.length?runBacktest({candles:normalized,strategy:strategyRegistry[strategyId],config,normalized:true}):null;
 if(inSample.length<minimum||outOfSample.length<minimum)return{strategyId,splitIndex,inSampleCandles:inSample.length,outOfSampleCandles:outOfSample.length,selectedParameters:null,inSample:null,outOfSample:null,outOfSampleScore:null,returnDecayPercent:null,scoreDecay:null,parameterStability:null,overfittingRisk:"UNAVAILABLE",robustnessScore:null,defaultThirtyDayResult};
 const sensitivity=runParameterSensitivity({candles:inSample,strategyId,config}),selected=sensitivity.highestScore;if(!selected)return{strategyId,splitIndex,inSampleCandles:inSample.length,outOfSampleCandles:outOfSample.length,selectedParameters:null,inSample:null,outOfSample:null,outOfSampleScore:null,returnDecayPercent:null,scoreDecay:null,parameterStability:null,overfittingRisk:"UNAVAILABLE",robustnessScore:null,defaultThirtyDayResult};
 const outResult=runBacktest({candles:outOfSample,strategy:createParameterizedStrategy(strategyId,selected.parameters),config,normalized:true}),outScore=calculateVeyrixScore(outResult.analytics).total,returnDecay=outResult.analytics.totalReturnPercent-selected.result.analytics.totalReturnPercent,scoreDecay=outScore-selected.veyrixScore,risk=classifyOverfitting(sensitivity.parameterStability,returnDecay,scoreDecay,selected.result.analytics.totalReturnPercent,outResult.analytics.totalReturnPercent),robustness=calculateRobustness(outScore,sensitivity.parameterStability,returnDecay,selected.result.analytics.maximumDrawdownPercent,outResult.analytics.maximumDrawdownPercent);
 return{strategyId,splitIndex,inSampleCandles:inSample.length,outOfSampleCandles:outOfSample.length,selectedParameters:selected.parameters,inSample:selected,outOfSample:outResult,outOfSampleScore:outScore,returnDecayPercent:returnDecay,scoreDecay,parameterStability:sensitivity.parameterStability,overfittingRisk:risk,robustnessScore:robustness,defaultThirtyDayResult};
}
export function runRobustnessArena(candles:readonly HistoricalCandle[],config:Readonly<BacktestConfig>):RobustnessArenaResult{const normalized=Object.freeze(normalizeHistoricalCandles(candles).candles.map(c=>Object.freeze({...c}))),entries=strategyList.map(strategy=>({strategyId:strategy.id,strategyName:strategy.name,report:runWalkForward(normalized,strategy.id,config)})),ranked=[...entries].sort((a,b)=>(b.report.robustnessScore??-1)-(a.report.robustnessScore??-1));return{entries,ranked,candleCount:normalized.length}}
